Update patch set 2
Patch Set 2: Verified-1

frameworks/native/libs/ui/GraphicBufferMapper.cpp: In member function 'android::status_t android::GraphicBufferMapper::lockAsync(buffer_handle_t, int, const android::Rect&, void**, int)':
frameworks/native/libs/ui/GraphicBufferMapper.cpp:123:30: error: 'sync_wait' was not declared in this scope
         sync_wait(fenceFd, -1);
                              ^
frameworks/native/libs/ui/GraphicBufferMapper.cpp: In member function 'android::status_t android::GraphicBufferMapper::lockAsyncYCbCr(buffer_handle_t, int, const android::Rect&, android_ycbcr*, int)':
frameworks/native/libs/ui/GraphicBufferMapper.cpp:145:30: error: 'sync_wait' was not declared in this scope
         sync_wait(fenceFd, -1);

Looks like GraphicBufferMapper.cpp needs to pull in sync/sync.h; I'll check this makes everything build locally and upload a new version.

Patch-set: 2
Label: Verified=-1